#!/bin/bash

export PATH=$PATH:$HOME/.opscore
version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r ".current_version")
current_version=$(terraform --version | grep 'Terraform' | cut -d ' ' -f 2  |  cut -c 2-)

if [ "$version" != "$current_version" ]; then
	echo "Upgrading to terraform version: $version"

	cd /tmp
	rm -rf terraform*
	wget --quiet -O terraform-"$version".zip https://releases.hashicorp.com/terraform/"$version"/terraform_"$version"_linux_amd64.zip
	echo "Unachiving..."
	unzip terraform-"$version".zip
	echo "Installing to ~/.opscore/terraform"
	cp terraform ~/.opscore/terraform
	terraform --version
	rm terraform-"$version".zip
else
	echo "Terraform is up to date: $current_version"
fi
